# Generated by Django 6.0.3 on 2026-04-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_otpverification_profile_is_phone_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='latitudeDelta',
            new_name='latitude_delta',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='longitudeDelta',
            new_name='longitude_delta',
        ),
    ]
