# Generated by Django 6.0.3 on 2026-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_otpverification_otp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpverification',
            old_name='code_hash',
            new_name='otp',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
