# Generated by Django 6.0.3 on 2026-05-08 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_profile_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='residence_members',
        ),
        migrations.AlterField(
            model_name='residence',
            name='residence_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residence',
            name='residence_members',
            field=models.ManyToManyField(related_name='residences', to=settings.AUTH_USER_MODEL),
        ),
    ]
