# Generated by Django 6.0.3 on 2026-05-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_groupchat_chatmessage_neighbourcommunity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude_delta',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude_delta',
        ),
    ]
